export const contactData = [
  {
    id: 1,
    contactOwner: "John Smith",
    accountName: "Acme Corporation",
    name: "Alice Johnson",
    email: "alice.j@acme.com",
    phone: "5551234567",
    createdDate: "15/01/2024",
    contactSource: "Website Form",
    contactStatus: "Active",
    contactBia: "Tier 1"
  },
  {
    id: 2,
    contactOwner: "Sarah Wilson",
    accountName: "Globex Inc",
    name: "Bob Williams",
    email: "bob.w@globex.com",
    phone: "5552345678",
    createdDate: "14/01/2026",
    contactSource: "Referral",
    contactStatus: "Pending",
    contactBia: "Tier 2"
  },
  {
    id: 3,
    contactOwner: "Mike Brown",
    accountName: "Initech",
    name: "Carol Davis",
    email: "carol.d@initech.com",
    phone: "5553456789",
    createdDate: "13/03/2024",
    contactSource: "Trade Show",
    contactStatus: "Idle",
    contactBia: "Tier 3"
  },
  {
    id: 4,
    contactOwner: "Emily Chen",
    accountName: "Umbrella Corp",
    name: "David Miller",
    email: "david.m@umbrella.com",
    phone: "5554567890",
    createdDate: "12/08/2024",
    contactSource: "Cold Call",
    contactStatus: "Active",
    contactBia: "Tier 1"
  },
  {
    id: 5,
    contactOwner: "Raj Patel",
    accountName: "Wayne Enterprises",
    name: "Eve Anderson",
    email: "eve.a@wayne.com",
    phone: "5555678901",
    createdDate: "11/09/2025",
    contactSource: "Email Campaign",
    contactStatus: "Pending",
    contactBia: "Tier 2"
  },
  {
    id: 6,
    contactOwner: "Lisa Wong",
    accountName: "Stark Industries",
    name: "Frank Martin",
    email: "frank.m@stark.com",
    phone: "5556789012",
    createdDate: "10/03/2024",
    contactSource: "Social Media",
    contactStatus: "Active",
    contactBia: "Tier 1"
  },
  {
    id: 7,
    contactOwner: "James Wilson",
    accountName: "Oscorp",
    name: "Grace Lee",
    email: "grace.l@oscorp.com",
    phone: "5557890123",
    createdDate: "09/10/2023",
    contactSource: "Partner",
    contactStatus: "Idle",
    contactBia: "Tier 3"
  },
  {
    id: 8,
    contactOwner: "Maria Garcia",
    accountName: "Cyberdyne",
    name: "Henry Clark",
    email: "henry.c@cyberdyne.com",
    phone: "5558901234",
    createdDate: "08/08/2023",
    contactSource: "Webinar",
    contactStatus: "Active",
    contactBia: "Tier 1"
  },
  {
    id: 9,
    contactOwner: "David Kim",
    accountName: "Tyrell Corp",
    name: "Ivy Taylor",
    email: "ivy.t@tyrell.com",
    phone: "5559012345",
    createdDate: "07/04/2023",
    contactSource: "Referral",
    contactStatus: "Pending",
    contactBia: "Tier 2"
  },
  {
    id: 10,
    contactOwner: "Sophia Martinez",
    accountName: "Weyland-Yutani",
    name: "Jack White",
    email: "jack.w@weyland.com",
    phone: "5550123456",
    createdDate: "06/04/2023",
    contactSource: "Trade Show",
    contactStatus: "Active",
    contactBia: "Tier 1"
  },
  {
    id: 11,
    contactOwner: "Daniel Nguyen",
    accountName: "Virtucon",
    name: "Karen Harris",
    email: "karen.h@virtucon.com",
    phone: "5551122334",
    createdDate: "05/04/2023",
    contactSource: "Advertisement",
    contactStatus: "Idle",
    contactBia: "Tier 3"
  },
  {
    id: 12,
    contactOwner: "Emma Davis",
    accountName: "Hooli",
    name: "Leo King",
    email: "leo.k@hooli.com",
    phone: "5552233445",
    createdDate: "04/04/2023",
    contactSource: "Website Form",
    contactStatus: "Active",
    contactBia: "Tier 1"
  },
  {
    id: 13,
    contactOwner: "Ryan Park",
    accountName: "Pied Piper",
    name: "Mia Scott",
    email: "mia.s@piedpiper.com",
    phone: "5553344556",
    createdDate: "03/04/2023",
    contactSource: "Referral",
    contactStatus: "Pending",
    contactBia: "Tier 2"
  },
  {
    id: 14,
    contactOwner: "Olivia Johnson",
    accountName: "Dunder Mifflin",
    name: "Noah Green",
    email: "noah.g@dundermifflin.com",
    phone: "5554455667",
    createdDate: "02/04/2023",
    contactSource: "Cold Call",
    contactStatus: "Active",
    contactBia: "Tier 1"
  },
  {
    id: 15,
    contactOwner: "Ethan Wilson",
    accountName: "Bluth Company",
    name: "Paula Brown",
    email: "paula.b@bluth.com",
    phone: "5555566778",
    createdDate: "01/04/2023",
    contactSource: "Email Campaign",
    contactStatus: "Idle",
    contactBia: "Tier 3"
  }
];